# Generated by Django 2.0.5 on 2018-05-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivebundler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Google',
        ),
    ]
